packages:
  - "apps/*"
  - "packages/*"
  - "engines/*"

allowBuilds:
  "@swc/core": true
  electron: true
  electron-winstaller: true
  esbuild: true

blockExoticSubdeps: false

onlyBuiltDependencies:
  - "@swc/core"
  - electron
  - electron-winstaller
  - esbuild
